// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQxwxLsizuBc99TkEG2kRMnfU0UWoo_E',
    appId: '1:337794451410:web:00ab4fc4d8a0592526ea0b',
    messagingSenderId: '337794451410',
    projectId: 'pricecomparisonwebsite-4c723',
    authDomain: 'pricecomparisonwebsite-4c723.firebaseapp.com',
    storageBucket: 'pricecomparisonwebsite-4c723.firebasestorage.app',
    measurementId: 'G-YP7EN9SPYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAlDqKjOItRzYDsYXB4acUxL7sdrf6lE',
    appId: '1:337794451410:android:896dd5895489bd9a26ea0b',
    messagingSenderId: '337794451410',
    projectId: 'pricecomparisonwebsite-4c723',
    storageBucket: 'pricecomparisonwebsite-4c723.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDchW6n-VKiYx0A8T07asyf03wOPLHqerE',
    appId: '1:337794451410:ios:ef8398f8eb6a637d26ea0b',
    messagingSenderId: '337794451410',
    projectId: 'pricecomparisonwebsite-4c723',
    storageBucket: 'pricecomparisonwebsite-4c723.firebasestorage.app',
    iosClientId: '337794451410-9i787jug1b8hnsm69opn03dvbq6586g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricePulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDchW6n-VKiYx0A8T07asyf03wOPLHqerE',
    appId: '1:337794451410:ios:ef8398f8eb6a637d26ea0b',
    messagingSenderId: '337794451410',
    projectId: 'pricecomparisonwebsite-4c723',
    storageBucket: 'pricecomparisonwebsite-4c723.firebasestorage.app',
    iosClientId: '337794451410-9i787jug1b8hnsm69opn03dvbq6586g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricePulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnFyhobxshDdAm5qvD8dY9WwAd_m8uXAQ',
    appId: '1:337794451410:web:4254a786560cccf326ea0b',
    messagingSenderId: '337794451410',
    projectId: 'pricecomparisonwebsite-4c723',
    authDomain: 'pricecomparisonwebsite-4c723.firebaseapp.com',
    storageBucket: 'pricecomparisonwebsite-4c723.firebasestorage.app',
    measurementId: 'G-Y94ZR57MM5',
  );
}
